services:
  api:
    container_name: hermes_api
    build: .
    env_file:
      - .env
    depends_on:
      - hermes_cache
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  hermes_cache:
    container_name: hermes_cache
    image: "redis:alpine"
volumes:
  pg_data: {}
